#!/usr/bin/env bash
# bootstrap-site.sh <reference-web-dir> <target-site-dir>
#
# Copies learn-claude-code's web app into a target project as the base for a
# learn.shareai.run-style tutorial, NEUTERS the predev/prebuild hooks (they run
# extract-content.ts which would clobber hand-authored content), and installs deps.
#
# Interactive mode: prompts for project type to preset constants.ts template.
# Verified on BondCode (Go). See REFERENCE.md.
set -euo pipefail

REF="${1:-}"
TGT="${2:-}"

if [ -z "$REF" ] || [ -z "$TGT" ]; then
  echo "usage: bootstrap-site.sh <reference-web-dir> <target-site-dir>" >&2
  echo "  e.g. bootstrap-site.sh /d/src/learn-claude-code/web /d/src/myproj/docs/site" >&2
  exit 1
fi
[ -d "$REF" ] || { echo "reference web dir not found: $REF" >&2; exit 1; }
[ -f "$REF/package.json" ] || { echo "not a web app (no package.json): $REF" >&2; exit 1; }

mkdir -p "$TGT"
# copy contents (cp -r is fine: node_modules/.next aren't committed in the reference)
cp -r "$REF"/. "$TGT"/

# Neuter extract hooks so npm run dev/build don't wipe hand-authored generated data.
if grep -q '"predev"' "$TGT/package.json"; then
  sed -i \
    -e 's#"predev": *"npm run extract"#"predev": "echo skip-extract (content hand-authored)"#g' \
    -e 's#"prebuild": *"npm run extract"#"prebuild": "echo skip-extract (content hand-authored)"#g' \
    "$TGT/package.json"
  echo "neutered predev/prebuild hooks."
fi

# Interactive project type selection
echo ""
echo "项目类型？(影响侧边栏分层和 hero 文案)"
echo "  1) Agent Runtime (默认) — 按 agent 生命周期分层"
echo "  2) CLI Tool           — 按命令行工具关注点（参数解析/子命令/错误处理）"
echo "  3) Web Service        — 按请求链路（路由/中间件/业务/存储）"
echo "  4) Data Pipeline      — 按数据流（采集/转换/存储/查询）"
echo "  5) Infra Kit          — 按基础设施组件（网络/存储/调度）"
read -p "输入 1-5 (默认 1): " PROJECT_TYPE
PROJECT_TYPE="${PROJECT_TYPE:-1}"

# Preset constants.ts template marker (Claude will read this and populate accordingly)
cat > "$TGT/.project-type" <<EOF
# Auto-generated by bootstrap-site.sh — read by Claude when authoring constants.ts
PROJECT_TYPE=$PROJECT_TYPE
EOF

case "$PROJECT_TYPE" in
  1) echo "→ Agent Runtime: 侧边栏将按 agent 生命周期分层 (tools → planning → memory → ...)" ;;
  2) echo "→ CLI Tool: 侧边栏将按 CLI 关注点分层 (parsing → commands → errors → ...)" ;;
  3) echo "→ Web Service: 侧边栏将按请求链路分层 (routing → middleware → business → ...)" ;;
  4) echo "→ Data Pipeline: 侧边栏将按数据流分层 (ingestion → transform → storage → ...)" ;;
  5) echo "→ Infra Kit: 侧边栏将按基础设施组件分层 (network → storage → scheduler → ...)" ;;
  *) echo "⚠ 未知类型，使用默认 Agent Runtime" ;;
esac

echo "installing deps (this is the long pole)..."
( cd "$TGT" && npm install )

cat <<EOF

DONE. Next:
  cd $TGT
  npx next dev -p 3000        # open http://localhost:3000/<locale>/<chapter>

Then hand-author content (see REFERENCE.md):
  src/lib/constants.ts                                  # VERSION_ORDER + VERSION_META + LAYERS (已预设项目类型模板提示)
  src/data/generated/versions.json                      # rm first (huge), then write {versions,diffs}
  src/data/generated/docs.json                          # [{version,locale,title,content(markdown)}]
  src/data/scenarios/<id>.json                          # simulator flow per chapter
  src/components/visualizations/index.tsx              # remap chapter ids -> viz components
  src/i18n/messages/<locale>.json                       # sessions/layer_labels/viz/meta titles
EOF
